// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYI9V3XK8i4O8LdM8RN8zmNuv9UcPwlRc',
    appId: '1:256767822565:android:d2cbcf41352786ef85e20c',
    messagingSenderId: '256767822565',
    projectId: 'shop-maintenance',
    storageBucket: 'shop-maintenance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTa5XFxN5AA2oJ3NKjW60CU1Ap1BBnbvM',
    appId: '1:256767822565:ios:63ab667a610cee9285e20c',
    messagingSenderId: '256767822565',
    projectId: 'shop-maintenance',
    storageBucket: 'shop-maintenance.appspot.com',
    androidClientId: '256767822565-0v39tqlsj8a2gmg94ug5guftebhpijhs.apps.googleusercontent.com',
    iosClientId: '256767822565-23aum8bli8rin1769lk7tapohj1meapc.apps.googleusercontent.com',
    iosBundleId: 'com.srisoftwarez.shopmaintenance',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKy4jPnQiWMTf7XN6mKZFzbVWgxKbZCkk',
    appId: '1:256767822565:web:e79390913da9257e85e20c',
    messagingSenderId: '256767822565',
    projectId: 'shop-maintenance',
    authDomain: 'shop-maintenance.firebaseapp.com',
    storageBucket: 'shop-maintenance.appspot.com',
    measurementId: 'G-3BEVREBHBK',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTa5XFxN5AA2oJ3NKjW60CU1Ap1BBnbvM',
    appId: '1:256767822565:ios:2908e0ea3e3e47cd85e20c',
    messagingSenderId: '256767822565',
    projectId: 'shop-maintenance',
    storageBucket: 'shop-maintenance.appspot.com',
    androidClientId: '256767822565-7c4qptrdk8s6at988bclfij2982mph5m.apps.googleusercontent.com',
    iosBundleId: 'com.srisoftwarez.shopmaintenanceDebug',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKy4jPnQiWMTf7XN6mKZFzbVWgxKbZCkk',
    appId: '1:256767822565:web:108a86976806673685e20c',
    messagingSenderId: '256767822565',
    projectId: 'shop-maintenance',
    authDomain: 'shop-maintenance.firebaseapp.com',
    storageBucket: 'shop-maintenance.appspot.com',
    measurementId: 'G-FGC22GTTET',
  );

}